// <auto-generated />
using System;
using AlgoLab.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlgoLab.Api.Migrations
{
    [DbContext(typeof(AlgoLabDbContext))]
    [Migration("20260922162818_AddRunData")]
    partial class AddRunData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AlgoLab.Api.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlgorithmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ApproximationCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxN")
                        .HasColumnType("INTEGER");

                    b.Property<double>("R2")
                        .HasColumnType("REAL");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("AlgoLab.Api.Models.ExperimentPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ApproximationTimeMs")
                        .HasColumnType("REAL");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAverage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Run")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ExperimentPoints");
                });

            modelBuilder.Entity("AlgoLab.Api.Models.ExperimentPoint", b =>
                {
                    b.HasOne("AlgoLab.Api.Models.Experiment", "Experiment")
                        .WithMany("Points")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("AlgoLab.Api.Models.Experiment", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
